---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                     5
        Log_Level                 info
        Daemon                    off
        Parsers_File              parsers.conf
        HTTP_Server               On
        HTTP_Listen               0.0.0.0
        HTTP_Port                 ${HTTP_PORT}
        storage.path              /var/fluent-bit/state/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 5M

    @INCLUDE application-log.conf

  application-log.conf: |
    [INPUT]
        Name                tail
        Path                /var/log/containers/server*.log
        Parser              docker
        Tag                 tc-server.*
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On

    [FILTER]
        Name                kubernetes
        Match               tc-server.*
        Buffer_Size         128k
        Merge_Log           On
        Merge_Log_Key       data
        Kube_Tag_Prefix     tc-server.var.log.containers.
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name                cloudwatch
        Match               tc-server.*
        region              ${AWS_REGION}
        log_group_name      /tc/clients/${CLUSTER_NAME}/$(kubernetes['namespace_name'])
        log_stream_name     $(kubernetes['container_name'])
        auto_create_group   true
        extra_user_agent    container-insights

  parsers.conf: |
    [PARSER]
        Name                docker
        Format              json
        Time_Key            time
        Tisme_Format         %Y-%m-%dT%H:%M:%S.%LZ
