apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  database.properties: |-
    connectionProperties.user={{.Values.db.user}}
    connectionProperties.password={{.Values.db.password}}
    connectionUrl=jdbc\:mysql\://{{.Values.db.url}}/{{.Values.db.name}}
